# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/esakat/gin-sample

    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
          name: テスト結果の保存場所作成
          command: mkdir -p $TEST_RESULTS
      - run:
          name: 依存ライブラリの取得
          command: go get -v -t -d ./...
      - run:
          name: junit-reportの取得
          command: go get -u github.com/jstemmer/go-junit-report
      - run:
          name: テスト実行
          #command: go test github.com/esakat/gin-sample/... -v  2>&1 | go-junit-report -set-exit-code=true > ${TEST_RESULTS}/report.xml
          command: go test ./... -v
      - store_test_results: #テスト結果の格納
          path: /tmp/test-results